---
- name: "Blacklistd: Stat /etc/rc.d/blacklistd"
  ansible.builtin.stat:
    path: /etc/rc.d/blacklistd
  register: pf_blacklistd_service

- name: "Blacklistd: Fail if blacklistd is enabled and no service exists"
  ansible.builtin.fail:
    msg: "[ERR] blacklistd is enabled, but no service exists."
  when:
    - pf_blacklistd_enable | bool
    - not pf_blacklistd_service.stat.exists

- name: "Blacklistd: Backup /etc/blacklistd.conf.orig"
  ansible.builtin.command:  # noqa: no-changed-when
    cmd: cp /etc/blacklistd.conf /etc/blacklistd.conf.orig
    creates: /etc/blacklistd.conf.orig
  when: pf_blacklistd_enable | bool

- name: "Blacklistd: Configure /etc/blacklistd.conf"
  ansible.builtin.template:
    dest: /etc/blacklistd.conf
    src: "{{ pf_blacklistd_template }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ pf_backup_conf }}"
  notify: restart blacklistd
  when: pf_blacklistd_enable | bool

# EOF
