---
- name: "Drop-lasso: Install periodic script."
  ansible.builtin.template:
    dest: /usr/local/etc/periodic/daily/900.drop-lasso
    src: "{{ pf_drop_lasso_template }}"
    owner: root
    group: wheel
    mode: "0755"
    # keeping a backup will result in the script being run multiple times
    backup: false
  when: pf_drop_lasso_enable | bool

- name: "Drop-lasso: Configure periodic."
  community.general.sysrc:
    path: "{{ pf_drop_lasso_periodic_file }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ pf_drop_lasso_periodic_conf }}"

- name: "Drop-lasso: set pf sysctl so you can load everything."
  ansible.posix.sysctl:
    sysctl_file: "{{ pf_drop_lasso_sysctl_file }}"
    name: net.pf.request_maxcount
    value: "{{ pf_drop_lasso_net_pf_request_maxcount }}"
    sysctl_set: true

# EOF
