---
- name: "Pfconf: Debug pf_debug={{ pf_debug }}"
  when: pf_debug | bool
  vars:
    msg: |-
      pf_type: {{ pf_type }}
      pf_ext_if: {{ pf_ext_if }}
      pf_conf_template: {{ pf_conf_template }}
      pf_conf_only: {{ pf_conf_only }}
      pf_conf_validate: {{ pf_conf_validate }}
      pf_conf_validate_command: {{ pf_conf_validate_command }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: Configure and validate /etc/pf.conf
  when: pf_conf_validate | bool
  block:

    - name: "Pfconf: Configure and validate rules using template {{ pf_conf_template }}"
      notify: reload pf
      ansible.builtin.template:
        dest: /etc/pf.conf
        src: "{{ pf_conf_template }}"
        owner: root
        group: wheel
        mode: "0640"
        backup: "{{ pf_backup_conf }}"
        validate: "{{ pf_conf_validate_command }}"

  rescue:

    - name: "Pfconf: Validation failed."
      ansible.builtin.fail:
        msg: "[ERR] Validation error: {{ ansible_failed_result }}"

- name: Configure and do not validate /etc/pf.conf
  when: not pf_conf_validate | bool
  block:

    - name: "Pfconf: Fail when pf_conf_validate=False and pf_conf_only=False"
      when: not pf_conf_only | bool
      ansible.builtin.fail:
        msg: "[ERR] Validation can be turned off if pf_conf_only=True."

    - name: "Pfconf: Configure and do not validate rules using template {{ pf_conf_template }}"
      ansible.builtin.template:
        dest: /etc/pf.conf
        src: "{{ pf_conf_template }}"
        owner: root
        group: wheel
        mode: "0640"
        backup: "{{ pf_backup_conf }}"

# EOF
