---
- name: Fail if relayd is enabled and no service exists.
  ansible.builtin.import_tasks: stat-relayd.yml

- name: Configure /etc/rc.conf or etc/rc.conf.d/relayd
  vars:
    _path: "{{ pf_rcconfd | bool | ternary('/etc/rc.conf.d/relayd', '/etc/rc.conf') }}"
  block:

    - name: "Rcconf-relayd: Enable and start relayd."
      when: pf_relayd_enable | bool
      notify:
        - start relayd
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: relayd_enable
        value: "YES"

    - name: "Rcconf-relayd: Disable and stop relayd."
      when: not pf_relayd_enable | bool
      notify:
        - stop relayd
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: relayd_enable
        value: "NO"

    - name: "Rcconf-relayd: Configure relayd."
      notify: restart relayd
      community.general.sysrc:
        path: "{{ _path }}"
        name: "{{ item.name }}"
        value: "{{ item.value | d(omit) }}"
        state: "{{ item.state | d(omit) }}"
      loop: "{{ pf_relayd_rcconf }}"

# EOF
