---
- name: Configure /etc/rc.conf or etc/rc.conf.d/relayd
  vars:
    _path: "{{ (pf_use_rc_conf_d | bool) | ternary('/etc/rc.conf.d/relayd', '/etc/rc.conf') }}"
  block:

    - name: "Rcconf-relayd: Enable and start relayd."
      when: pf_relayd_enable | bool
      notify:
        - enable and start relayd
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: relayd_enable
        value: "YES"

    - name: "Rcconf-relayd: Disable and stop relayd."
      when: not pf_relayd_enable | bool
      notify:
        - disable and stop relayd
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: relayd_enable
        value: "NO"

    - name: "Rcconf-relayd: Configure relayd."
      notify: restart relayd
      community.general.sysrc:
        path: "{{ _path }}"
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop: "{{ pf_relayd_rcconf }}"

# EOF
