---
- name: Fail if sshguard is enabled and no service exists.
  when:
    - pf_sshguard_enable | bool
    - pf_sshguard_stat is undefined
  block:

    - name: "Rcconf-sshguard: Stat /usr/local/etc/rc.d/sshguard"
      register: pf_sshguard_stat
      ansible.builtin.stat:
        path: /usr/local/etc/rc.d/sshguard

    - name: "Rcconf-sshguard: Fail if sshguard is enabled and no service exists."
      when: not pf_sshguard_stat.stat.exists
      ansible.builtin.fail:
        msg: "[ERR] sshguard is enabled, but no service exists."

- name: Configure /etc/rc.conf or etc/rc.conf.d/sshguard
  vars:
    _path: "{{ pf_rcconfd | bool | ternary('/etc/rc.conf.d/sshguard', '/etc/rc.conf') }}"
  block:

    - name: "Rcconf-sshguard: Enable and start sshguard."
      when: pf_sshguard_enable | bool
      notify: start sshguard
      community.general.sysrc:
        path: "{{ _path }}"
        name: sshguard_enable
        value: "YES"

    - name: "Rcconf-sshguard: Disable and stop sshguard."
      when: not pf_sshguard_enable | bool
      notify: stop sshguard
      community.general.sysrc:
        path: "{{ _path }}"
        name: sshguard_enable
        value: "NO"

# EOF
