---
- name: Fail if blacklistd is enabled and no service exists.
  when:
    - pf_blacklistd_enable | bool
    - pf_blacklistd_stat is undefined
  block:

    - name: "Rcconf-blacklistd: Stat /etc/rc.d/blacklistd"
      register: pf_blacklistd_stat
      ansible.builtin.stat:
        path: /etc/rc.d/blacklistd

    - name: "Rcconf-blacklistd: Fail if blacklistd is enabled and no service exists."
      when: not pf_blacklistd_stat.stat.exists
      ansible.builtin.fail:
        msg: "[ERR] blacklistd is enabled, but no service exists."

- name: Configure /etc/rc.conf or etc/rc.conf.d/blacklistd
  vars:
    _path: "{{ pf_rcconfd | bool | ternary('/etc/rc.conf.d/blacklistd', '/etc/rc.conf') }}"
  block:

    - name: "Rcconf-blacklistd: Enable and start blacklistd."
      when: pf_blacklistd_enable | bool
      notify:
        - start blacklistd
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: blacklistd_enable
        value: "YES"

    - name: "Rcconf-blacklistd: Disable and stop blacklistd."
      when: not pf_blacklistd_enable | bool
      notify:
        - stop blacklistd
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: blacklistd_enable
        value: "NO"

    - name: "Rcconf-blacklistd: Configure blacklistd."
      notify: restart blacklistd
      community.general.sysrc:
        path: "{{ _path }}"
        name: "{{ item.name }}"
        value: "{{ item.value | d(omit) }}"
        state: "{{ item.state | d(omit) }}"
      loop: "{{ pf_blacklistd_rcconf }}"

# EOF
