---
- name: Configure /etc/rc.conf or etc/rc.conf.d/fail2ban
  vars:
    _path: "{{ (pf_use_rc_conf_d | bool) | ternary('/etc/rc.conf.d/fail2ban', '/etc/rc.conf') }}"
  block:

    - name: "Rcconf-fail2ban: Check if fail2ban is installed."
      register: service_status
      ansible.builtin.stat:
        path: /usr/local/etc/rc.d/fail2ban

    - name: "Rcconf-fail2ban: Enable and start fail2ban."
      when:
        - pf_fail2ban_enable | bool
        - service_status.stat.exists
      notify:
        - enable and start fail2ban
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: fail2ban_enable
        value: "YES"

    - name: "Rcconf-fail2ban: Disable and stop fail2ban."
      when:
        - not pf_fail2ban_enable | bool
        - service_status.stat.exists
      notify:
        - disable and stop fail2ban
        - reload pf
      community.general.sysrc:
        path: "{{ _path }}"
        name: fail2ban_enable
        value: "NO"

    - name: "Rcconf-fail2ban: Configure fail2ban."
      notify: restart fail2ban
      community.general.sysrc:
        path: "{{ _path }}"
        name: "{{ item.regexp }}"
        value: "{{ item.line }}"
      loop: "{{ pf_fail2ban_rcconf }}"

# EOF
