---
- name: "Relayd: Debug pf_debug={{ pf_debug }}"
  when: pf_debug | bool
  vars:
    msg: |-
      pf_relayd_template: {{ pf_relayd_template }}
      pf_relayd_conf_only: {{ pf_relayd_conf_only }}
      pf_relayd_conf_validate: {{ pf_relayd_conf_validate }}
      pf_relayd_conf_validate_command: {{ pf_relayd_conf_validate_command }}

      pf_relayd_macros:
        {{ pf_relayd_macros | to_nice_yaml(indent=2) | indent(2) }}
      pf_relayd_options:
        {{ pf_relayd_options | to_nice_yaml(indent=2) | indent(2) }}
      pf_relayd_tables:
        {{ pf_relayd_tables | to_nice_yaml(indent=2) | indent(2) }}
      pf_relayd_redirections:
        {{ pf_relayd_redirections | to_nice_yaml(indent=2) | indent(2) }}
      pf_relayd_protocols:
        {{ pf_relayd_protocols | to_nice_yaml(indent=2) | indent(2) }}
      pf_relayd_relays:
        {{ pf_relayd_relays | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: Fail if relayd is enabled and no service exists.
  ansible.builtin.import_tasks: stat-relayd.yml

- name: Configure and validate /usr/local/etc/relayd.conf
  when: pf_relayd_conf_validate | bool
  block:

    - name: "Relayd: Configure and validate /usr/local/etc/relayd.conf"
      notify: reload relayd
      ansible.builtin.template:
        dest: /usr/local/etc/relayd.conf
        src: "{{ pf_relayd_template }}"
        owner: root
        group: wheel
        mode: "0644"
        backup: "{{ pf_backup_conf }}"
        validate: "{{ pf_relayd_conf_validate_command }}"

  rescue:

    - name: "Relayd: Validation failed."
      ansible.builtin.fail:
        msg: "[ERR] Validation error: {{ ansible_failed_result }}"

- name: Configure and do not validate /usr/local/etc/relayd.conf
  when: not pf_relayd_conf_validate | bool
  block:

    - name: "Relayd: Fail when pf_relayd_conf_validate=False and pf_relayd_conf_only=False"
      when: not pf_relayd_conf_only | bool
      ansible.builtin.fail:
        msg: "[ERR] Validation can be turned off if pf_relayd_conf_only=True."

    - name: "Relayd: Configure and do not validate /usr/local/etc/relayd.conf"
      ansible.builtin.template:
        dest: /usr/local/etc/relayd.conf
        src: "{{ pf_relayd_template }}"
        owner: root
        group: wheel
        mode: "0644"
        backup: "{{ pf_backup_conf }}"

# EOF
