---
- name: Fail if sshguard is enabled and no service exists.
  when: pf_sshguard_enable | bool
  block:

    - name: "Sshguard: Stat /usr/local/etc/rc.d/sshguard"
      register: pf_sshguard_service
      ansible.builtin.stat:
        path: /usr/local/etc/rc.d/sshguard

    - name: "Sshguard: Fail if sshguard is enabled and no service exists."
      when: not pf_sshguard_service.stat.exists
      ansible.builtin.fail:
        msg: "[ERR] sshguard is enabled, but no service exists."

- name: "Sshguard: Configure pf whitelist sshguard"
  notify: restart sshguard
  ansible.builtin.lineinfile:
    dest: /usr/local/etc/sshguard.whitelist
    line: "{{ item }}"
    backup: "{{ pf_backup_conf }}"
  loop: "{{ pf_ssh_whitelist }}"

# EOF
