---
- name: Fail if sshguard is enabled and no service exists.
  ansible.builtin.import_tasks: stat-sshguard.yml

- name: "Sshguard: Configure pf whitelist sshguard"
  notify: restart sshguard
  ansible.builtin.lineinfile:
    dest: /usr/local/etc/sshguard.whitelist
    line: "{{ item }}"
    backup: "{{ pf_backup_conf }}"
  loop: "{{ pf_ssh_whitelist }}"

# EOF
