---
# handlers for freebsd_pf

- name: Start blacklistd
  listen: start blacklistd
  ansible.builtin.service:
    name: blacklistd
    state: started

- name: Stop blacklistd
  listen: stop blacklistd
  ansible.builtin.service:
    name: blacklistd
    state: stopped

- name: Restart blacklistd
  listen: restart blacklistd
  when: pf_blacklistd_enable | bool
  ansible.builtin.service:
    name: blacklistd
    state: restarted

# EOF
