---
# handlers for freebsd_pf

- name: Start fail2ban
  listen: start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started

- name: Stop fail2ban
  listen: stop fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: stopped

- name: Restart fail2ban
  listen: restart fail2ban
  when: pf_fail2ban_enable | bool
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reload fail2ban
  listen: reload fail2ban
  when: pf_fail2ban_enable | bool
  ansible.builtin.service:
    name: fail2ban
    state: reloaded

# EOF
