---
# handlers for freebsd_pf

- name: Start relayd
  listen: start relayd
  when: not pf_relayd_conf_only | bool
  ansible.builtin.service:
    name: relayd
    state: started

- name: Stop relayd
  listen: stop relayd
  ansible.builtin.service:
    name: relayd
    state: stopped

- name: Restart relayd
  listen: restart relayd
  when:
    - pf_relayd_enable | bool
    - not pf_relayd_conf_only | bool
  ansible.builtin.service:
    name: relayd
    state: restarted

- name: Reload relayd
  listen: reload relayd
  when:
    - pf_relayd_enable | bool
    - not pf_relayd_conf_only | bool
  ansible.builtin.service:
    name: relayd
    state: reloaded

# EOF
