---
# handlers for freebsd_pf

- name: Start sshguard
  listen: start sshguard
  ansible.builtin.service:
    name: sshguard
    state: started

- name: Stop sshguard
  listen: stop sshguard
  ansible.builtin.service:
    name: sshguard
    state: stopped

- name: Restart sshguard
  listen: restart sshguard
  when: pf_sshguard_enable | bool
  ansible.builtin.service:
    name: sshguard
    state: restarted

# EOF
